---
# tasks file for engine-external

- name: create cron entry for secure logbook operations
  cron:
    name: "Secure logbook operations"
    minute: "1"
    hour: "0"
    user: "{{ vitam_user }}"
    job: "/vitam/script/logbook/launchTraceability.sh"
  run_once: yes
  delegate_to: "{{ groups['hosts-logbook'] | last }}"